# Generated by Django 5.2.12 on 2026-03-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('working_hours_start', models.TimeField(blank=True, default='08.00', null=True)),
                ('working_hours_end', models.TimeField(blank=True, default='18.00', null=True)),
                ('appointment_duration', models.IntegerField(default=60)),
                ('login_identifier', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=100)),
                ('session_timer', models.IntegerField(blank=True, default=30, null=True)),
                ('max_failed_logins', models.PositiveIntegerField(blank=True, default=10, null=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('notify_on_appointment', models.BooleanField(default=True)),
                ('notify_on_bill', models.BooleanField(default=True)),
                ('notify_on_report', models.BooleanField(default=True)),
                ('doctor_requires_approval', models.BooleanField(default=True)),
                ('operator_requires_approval', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('hospital', 'Hospital Blue')], default='hospital', max_length=100)),
                ('primary_color', models.CharField(default='#0d6efd', max_length=100)),
                ('sidebar_collapsible', models.BooleanField(default=True)),
                ('report_confidentiality', models.BooleanField(default=False)),
                ('activity_logging', models.BooleanField(default=False)),
                ('data_retention_days', models.PositiveIntegerField(default=365, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
