# Generated by Django 5.2.12 on 2026-05-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='email_host',
            field=models.CharField(default='smtp.email.com', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_host_password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_host_user',
            field=models.CharField(default='noreply@hospital.com', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='factor_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicons/'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='password_expiry',
            field=models.PositiveIntegerField(blank=True, default=120, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='site_name',
            field=models.CharField(default='Hospital Management System', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sms_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sms_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sms_provider',
            field=models.CharField(default='Twilio', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='twilio_account_sid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='twilio_auth_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='max_failed_logins',
            field=models.PositiveIntegerField(blank=True, default=3, null=True),
        ),
    ]
