# Generated by Django 5.2.12 on 2026-03-31 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_hours_start', models.TimeField()),
                ('working_hours_end', models.TimeField()),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('leave_dates', models.JSONField(blank=True, default=list)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
            ],
        ),
    ]
