# Generated by Django 5.2.12 on 2026-05-04 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='object_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View Records'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('EXPORT', 'Export'), ('EMAIL', 'Email'), ('EMERGENCY_OVERRIDE', 'EMERGENCY Override'), ('REPORT_GENERATE', 'REPORT GENERATE')], default='CREATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_photos/'),
        ),
        migrations.CreateModel(
            name='AdminReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('users', 'User Report'), ('doctors', 'Doctor Report'), ('patients', 'Patient Report'), ('billing', 'Billing Report'), ('audit', 'Audit Log Report'), ('custom', 'Custom Report')], max_length=100)),
                ('format', models.CharField(choices=[('pdf', 'PDF Document'), ('excel', 'Excel Spreadsheet'), ('csv', 'CSV File'), ('json', 'JSON Data')], default='pdf', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('date_range_start', models.DateTimeField(blank=True, null=True)),
                ('date_range_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_download_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_download_at'],
            },
        ),
    ]
