# Generated by Django 5.2.12 on 2026-05-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_object_type_auditlog_success_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorfield',
            name='staff_photo',
            field=models.ImageField(blank=True, null=True, upload_to='operator_photos/'),
        ),
    ]
