# Generated by Django 5.2.12 on 2026-06-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_operatorfield_staff_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='priority',
            field=models.CharField(default='Normal', max_length=100),
        ),
    ]
