# Generated by Django 5.2.12 on 2026-03-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_critical', models.BooleanField(default=False)),
                ('report_file', models.FileField(upload_to='lab_results/')),
                ('remarks', models.TextField(null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent_to_doctor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='labRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('blood', 'blood_test'), ('urine', 'urine_test'), ('X-Ray', 'X-Ray'), ('pathology', 'Pathology'), ('radiology', 'Radiology'), ('other', 'other')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('sample_taken', 'Sample Taken'), ('ready', 'Ready'), ('cancelled', 'Cancelled')], default='Requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('available', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=120)),
                ('is_available', models.BooleanField(default=True)),
                ('qualifications', models.TextField()),
                ('license_number', models.CharField(max_length=100)),
            ],
        ),
    ]
