# Generated by Django 5.2.12 on 2026-05-04 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('description_type', models.CharField(max_length=100)),
                ('fasting_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='labreport',
            name='quality_control_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='quality_control_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='labreport',
            name='structured_results',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='structured_results',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='test_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labtech',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='lab_photos'),
        ),
        migrations.CreateModel(
            name='TestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('reference_range_low', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('reference_range_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('reference_range_text', models.CharField(blank=True, max_length=200)),
                ('decimal_places', models.IntegerField(default=1)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_critical', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=True)),
                ('test_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='Lab.testprofile')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='labrequest',
            name='test_profile',
            field=models.ForeignKey(help_text='Test profile defining expected parameters.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Lab.testprofile'),
        ),
    ]
